### ISSUE TITLE
Updates to homepage wireframe

### ISSUE THREAD

**Issue by kaylima** [INN/inn#26]
Left Sidebar:
- [x] Move Events to the left sidebar
- [x] Remove left sidebar membership button
- [x] Remove the list of services (will be in the nav drop-down)
- [x] Keep the subdomains w/ logos at top of sidebar (above Events)

Main Image:
- [x] Update main hero image to 3/4 rather than 2/3 width (network news = 1/4)
- [x] Hero image should be full color (make hero images less newsy, more about advocacy)
- [x] Different treatment for hero image messaging (instead of the block of color w/ text)

Misc.:
- [x] Remove membership directory from homepage
- [x] Make member area bigger (like the previous version before events was added)
- [x] Keep buttons as INN blue
- [x] Links should **NOT** have a blue font color. Explore other options for links (such as underlines, etc.)

**Comment by gabehong** [comment]
new wireframes at https://www.dropbox.com/s/0t1mmglgyqo42ur/Inn-homepage-wireframes-v2.pdf?dl=0

**Comment by julia67** [comment]
**Global:**
- [ ] Add very slight drop shadow to all blue buttons for readability
- [ ] Square corners on newsletter signup field 
- [ ] If buttons are caps, the donate button should be caps too
- [ ] Remove extraneous horizontal rules
- [ ] Headline hover color should stay #000, remove the hover preview from the member headline in the mockup
- [ ] Sign-up box should have same treatment on both INN and Learn sites (preferably the grey screen)

**Homepage:**
- [ ] Dashed line in events box seems out of place, try solid in a lighter color
- [ ] Network News headlines should be slightly smaller
- [ ] Events should probably be a list with a “see more” button instead of a scrolling box
- [ ] Photo header text needs to be in a format we can create programmatically (probably same size and aligned left or center)
- [ ] Update navigation with site map items
- [ ] Sign-up box and events box should use the same color grey

**Questions for stakeholder:**
- [ ] Nowhere on the homepage does it explain what we do, how to become a member, the services we offer, or how to hire us …is that a problem?

**Comment by gabehong** [comment]
new pdf at https://www.dropbox.com/s/hix42z6b6km44o0/Inn-homepage-wireframes-v3.pdf?dl=0

**Comment by kaylima** [comment]
- [ ] Elements consistent across brands (labs and inn.org/learn) - Can (and should) we use the same signups, logo size, etc? @julia67: Please weigh in on this.
- [ ] Newsletter signup text: "INNovation! Get the weekly newsletter.”
- [ ] Promo space: show in mockup. Which color to use? @julia67 
- [ ] New layout:
1. Hero (top of homepage)
2. INN Mission (top of homepage to right of hero)
3. Events (1st column)
4. From INN (formerly "Network News", 2nd column)
5. From Our Members (3rd column)
- [ ] From INN and From Our Members = 1 image above post title and excerpt
- [ ] Events = 1 image above ... ? TBD @gabehong you can play around with this
- [ ] Remove INNovation from global nav

**Comment by gabehong** [comment]
New PDF at https://www.dropbox.com/s/sp1g37oai24su9h/Inn-homepage-wireframes-v5.pdf?dl=0
FONTS:
`font-family: "effra", helvetica, sans-serif`

COLORS:
INN Blue `color: #09c9ff`
Black: `color: #000`
White: `color: #fff`
Events/Newsletter Light Gray Background: `color: #f2f2f2`
Events Dark Gray Header: `color: #4d4d4d`
Footer Background: `color: #1a1a1a;`

**Comment by benlk** [comment]
mobile wireframe: https://www.dropbox.com/s/bww4wiollngw2dl/Inn-homepage-wireframes-v5-mobile.pdf?dl=0

For the events, does any of the styling change there if there is no image for the image?

**Comment by gabehong** [comment]
Yeah, I'd probably fill that space with an excerpt of the event copy. Like below
![screen shot 2017-06-22 at 9 50 00 am](https://user-images.githubusercontent.com/14035072/27445876-55d413de-5730-11e7-88af-93161abab4ce.png)

(Thoughts @kaylima?)

Final wireframe PDF updated at https://www.dropbox.com/s/sp1g37oai24su9h/Inn-homepage-wireframes-v5.pdf?dl=0

**Comment by kaylima** [comment]
Agreed! Thanks, @gabehong.

**Comment by kaylima** [comment]
@gabehong what are the font weights for headers, etc?

**Comment by gabehong** [comment]
## Effra Font bold
`font-weight: 700;`
- [ ] All Headers
- [ ] Footer Mission Statement
- [ ] Events Widget Title
- [ ] All Buttons
- [ ] Hero Image Text Overlay
- [ ] Generally all links (including Testimonial Organization Name)

## Effra Font regular
`font-weight: 400;`
- [ ] Testimonial
- [ ] Newsletter copy
- [ ] Main Nav/Footer
- [ ] Promo Banner copy
- [ ] INN Mission Statement (next to hero image)

## Effra Font light
`font-weight: 300;`
- [ ] Category tags
- [ ] Event widget date
- [ ] From INN/From Our Members Excerpt
- [ ] From our Members Organization Name
- [ ] Address/e-mail/phone number and Privacy Statement/Bylaws in Footer

**Comment by benlk** [comment]
Is the Events widget shown here supposed to be a widget that currently exists? It doesn't seem to match any of the ones provided by the plugins The Events Calendar, The Events Calendar Pro, or The Events Calendar: Eventbrite Tickets.

**Comment by benlk** [comment]
@gabehong, can you upload or link to the image used for the "We Raise Voices" area on the homepage?
